// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTtEB4Nk9jCW-xKTD-bEzgNF5hXkVNPK0',
    appId: '1:511823829492:web:243f4188f1d9fe6b9981a1',
    messagingSenderId: '511823829492',
    projectId: 'rfid-6301d',
    authDomain: 'rfid-6301d.firebaseapp.com',
    storageBucket: 'rfid-6301d.firebasestorage.app',
    measurementId: 'G-VZCQERW1BP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPo47EJyNnGrJjgJfkZmhUw45oiemWaRA',
    appId: '1:511823829492:android:f7902e14550f203b9981a1',
    messagingSenderId: '511823829492',
    projectId: 'rfid-6301d',
    storageBucket: 'rfid-6301d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgz-vFU-jpT5D9wtMP93sS_6v1hBSO4O4',
    appId: '1:511823829492:ios:97ff107b8f7ed8c49981a1',
    messagingSenderId: '511823829492',
    projectId: 'rfid-6301d',
    storageBucket: 'rfid-6301d.firebasestorage.app',
    iosBundleId: 'com.example.empty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgz-vFU-jpT5D9wtMP93sS_6v1hBSO4O4',
    appId: '1:511823829492:ios:97ff107b8f7ed8c49981a1',
    messagingSenderId: '511823829492',
    projectId: 'rfid-6301d',
    storageBucket: 'rfid-6301d.firebasestorage.app',
    iosBundleId: 'com.example.empty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTtEB4Nk9jCW-xKTD-bEzgNF5hXkVNPK0',
    appId: '1:511823829492:web:9b5ad68403d14a659981a1',
    messagingSenderId: '511823829492',
    projectId: 'rfid-6301d',
    authDomain: 'rfid-6301d.firebaseapp.com',
    storageBucket: 'rfid-6301d.firebasestorage.app',
    measurementId: 'G-GL6B6E6EGY',
  );
}
